name: DeathSwap
main: com.amazansky.deathswap.DSMainPlugin
version: 0.1.0
author: amazansky
description: This plugin enables you to play the deathswap game originally made by SethBling, but with swaps every fixed amount of time as popularized by Dream.

api-version: 1.15 # TODO: Make sure this is compatible with MC version 1.14

commands:
  dsgame:
    # TODO: Permissions for admin stuff/not
    usage: "Usage: /<command> [join | leave | start | stop | settings | info]"
    permission: dsgame
    permission-message: "You don't have the permission to execute this command."

permissions:
  dsgame:
    default: true
    description: "Gives access to '/dsgame' commands"